- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512') }}"
    state: present
    shell: /bin/bash
    groups: wheel, users
